[package]
name = "arboretum"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
clap = "4.5.13"
simple-triplestore = {path="../../triplestore/"}
tokio = { version = "1.39.2", features = ["rt-multi-thread"] }
ulid = "1.1.3"
